apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","automountServiceAccountToken":false,"kind":"ServiceAccount","metadata":{"annotations":{},"name":"demo-app","namespace":"secure"}}
  creationTimestamp: "2026-06-08T15:21:50Z"
  name: demo-app
  namespace: secure
  resourceVersion: "28645"
  uid: 7bd7295a-5146-4e77-a965-64ca97187573
