apiVersion: v1
data:
  API_TOKEN: ZGVtby10b2tlbi1iZWZvcmUtcGxhaW50ZXh0
  DB_PASSWORD: ZGVtby1wYXNzd29yZC1iZWZvcmUtcGxhaW50ZXh0
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"demo-app-secret","namespace":"vulnerable"},"stringData":{"API_TOKEN":"demo-token-before-plaintext","DB_PASSWORD":"demo-password-before-plaintext"},"type":"Opaque"}
  creationTimestamp: "2026-06-08T15:08:49Z"
  name: demo-app-secret
  namespace: vulnerable
  resourceVersion: "24818"
  uid: 2ed5237e-648f-4e96-a699-b133070a667b
type: Opaque
